---
language: node_js
node_js: 6

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

# env forces jobs to be created from the top level settings
env:
jobs:
  include:
    - stage: moban
      language: python
      python: 3.6
      apt: false
      cache: pip
      before_install: false
      install: pip install moban
      before_script: false
      script: .ci/check_moban.sh
      after_script: false
      after_success: false
      after_failure: false
      before_deploy: false
      deploy: false
      after_deploy: false
      before_cache: false

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install
  - npm install -g ember-cli

script:
  - npm test

before_deploy:
  - ember build --env production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
  name: Yana Agun Siswanto
  email: yana.developer@gmail.com
