---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

.disable_global: &disable_global
  node_js: false
  cache: false
  before_install: false
  install: false
  before_script: false
  script: false
  after_success: false
  before_deploy: false
  deploy: false

# env forces jobs to be created from the top level settings
env:
jobs:
  include:
    - <<: *disable_global
      stage: moban
      language: python
      python: 3.6
      cache: pip
      install: pip install moban
      script: .ci/check_moban.sh

before_install:
  - npm config set spin false

before_script:
  - bower install

script:
  - npm test

after_success:
  - codecov

before_deploy:
  - ember build --env production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
  name: Yana Agun Siswanto
  email: yana.developer@gmail.com
