---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false

before_script:
  - bower install

script:
  - npm test

before_deploy:
  - ember build --env production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
  name: Yana Agun Siswanto
  email: yana.developer@gmail.com
